### ISSUE TITLE
Launch into AnyWorkflow 

### ISSUE THREAD

**Issue by trevor-holliday** [wwt/SwiftCurrent#102]
### Is your feature request related to a problem? Please describe.
I am using the Type erased AnyWorkflow, but I am unable to launch that erased workflow. 

### Describe the solution you'd like
Following a similar pattern to a Type Specified Workflow, I want to be able to call `launchInto(AnyWorkFlow)`

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Tyler-Keith-Thompson** [comment]
Thanks for the feature request! We'll work on this and get back to you.

**Comment by Tyler-Keith-Thompson** [comment]
Version 4.3.8 was just released and should have your enhancement in it!
