### ISSUE TITLE
XCFramework for SwiftCurrent_Testing

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [wwt/SwiftCurrent#110]
We've got other XCFrameworks for all of our packages except for SwiftCurrent_Testing. It would be good to add that as well, if we can.

**Comment by Tyler-Keith-Thompson** [comment]
It's just another distribution mechanism. I personally feel people should use package managers for a whole host of reasons. That said, there are reasons why people avoid them. For those who want to link to a framework themselves we provide a static framework to link against.

**Comment by morganzellers** [comment]
We will likely be closing this issue, as this is currently not supported with the build tools we use in the pipeline. Additional context for this can be found on the associated PR #149, [here](https://developer.apple.com/forums/thread/125921), and [here](https://developer.apple.com/forums/thread/650163).

**Comment by nickkaczmarek** [comment]
@morganzellers we'll likely want to take a gander at docs to make this explainable to consumers, but writing this to remind myself as well.

**Comment by morganzellers** [comment]
@nickkaczmarek I'll take a look today and see if there's an appropriate place

**Comment by nickkaczmarek** [comment]
@morganzellers we may also want to see if there is a way we can zip it up as not a framework in our release.

**Comment by morganzellers** [comment]
@nickkaczmarek that's a good point... I'm gonna chase that down for a bit

**Comment by morganzellers** [comment]
So after looking into this, I thought we may be able to archive our test target or wrap it in a project file but it looks like there's not really support for that. Would providing individual test files zipped be of use? I'm not sure.

**Comment by nickkaczmarek** [comment]
@morganzellers I think it would be worth doing a regular zip on this because we're sort of supporting an edge case where someone might want to use the project, but isn't interested in using a package manager.

**Comment by morganzellers** [comment]
We will not be offering an XCFramework for the testing package due to the feature differences between `xcodebuild` and `swift build.` 

See PR #149 for more context. While we will not offer a static framework file for the testing package, we do so for the three main packages, `SwiftCurrent,` `SwiftCurrent_SwiftUI,` and `SwiftCurrent_UIKit.` Users should still be able to try out the library, and should they wish to see the tests themselves, we upload compressed source code with each release.
