### ISSUE TITLE
Allow `thenProceed` in preview providers

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [wwt/SwiftCurrent#156]
### Is your feature request related to a problem? Please describe.
I want to use previews to view my `FlowRepresentable` as it'll appear in a workflow, even if that's just a single item workflow. However, right now `thenProceed` is not available.

### Describe the solution you'd like
Either make `thenProceed` globally available so we quit having one-off "I need it added" or add it to `PreviewProvider`.

### Describe alternatives you've considered
I could write my own extension for this, but it should just work out of the box. Additionally, I suppose we could wrap `thenProceed` in some new protocol? However, I don't like the idea that I have to conform to a protocol just to define a workflow. There may be something to investigating resultBuilders in a future version of Swift where they allow those scoped functions. I've seen proposals about it, but for now I don't think we should go that route.

**Comment by Tyler-Keith-Thompson** [comment]
Even hacky workarounds are proving difficult

<img width="1056" alt="Screen Shot 2021-12-11 at 1 50 10 PM" src="https://user-images.githubusercontent.com/33705774/145691218-293550a3-d9a9-4c4f-8906-c4482a6a5d70.png">

**Comment by Tyler-Keith-Thompson** [comment]
For anybody who might also be stuck here's a horrible workaround:

```swift
struct HomeView_Previews: PreviewProvider {
    struct WF: View {
        var body: some View {
            WorkflowLauncher(isLaunched: .constant(true)) {
                thenProceed(with: HomeView.self)
                    .presentationType(.navigationLink)
            }.embedInNavigationView()
        }
    }

    static var previews: some View { WF() }
}

```

**Comment by nickkaczmarek** [comment]
Closing because this is working and has been merged.

**Comment by Tyler-Keith-Thompson** [comment]
Please reopen. This was not merged to main. It isn't available for consumers because it was a breaking change

**Comment by nickkaczmarek** [comment]
I'll reopen but I'm a little confused. I was able to see the ContentView in the SwiftUI sample rendering correctly while using the preview canvas. Unless you're saying that you can't write `thenProceed` in the previewprovider, but I'm not sure why that would be a thing we'd want to do. My impression was that you just put the view into the previewprovider and if that rendered then you're good.

**Comment by nickkaczmarek** [comment]
I think the part about showing a view in context and also showing a view in multiple states makes sense to me. I've only used previews to visual the design of things as well as show views within other views. The views within other views sounds like what you're talking about here, albeit with views inside of workflows so I think this is a reasonable ask. 

I don't normally mind using the simulator or clicking the play button on the canvas, but I could imagine that being heavier in some cases.

---
It sounds like making `thenProceed` static is likely the way to go, but there might be a fancier way to achieve that as well.

**Comment by Tyler-Keith-Thompson** [comment]
#179 invalidates this issue as a thing. The new SwiftUI API lends itself much better to all use-cases.
