### ISSUE TITLE
[Feature]: Allow XCTAssertWorkflowLaunched to accept AnyWorkflow

### ISSUE THREAD

**Issue by nallick** [wwt/SwiftCurrent#208]
### What prompted this feature request?

Creating a data driven workflow gives me a type erased `AnyWorkflow`. I want to be able to write a unit test to ensure said workflow was launched, however `XCTAssertWorkflowLaunched()` is generic on the workflow's `FlowRepresentable` type and this can't be determined for a type erased workflow.

### Describe the solution you'd like

Provide an overloaded non-generic version of `XCTAssertWorkflowLaunched()` that accepts `AnyWorkflow`.

### Describe alternatives you've considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tyler-Keith-Thompson** [comment]
Released in Fixed in 5.1.6
