### ISSUE TITLE
Create github pages for current library name to host Developer docs and wiki.

### ISSUE THREAD

**Issue by Richard-Gist** [wwt/SwiftCurrent#34]
Splitable: Add to the pipeline pushing to that repo.

Milestone: [Great Onboarding Experience](https://github.com/wwt/Workflow/milestone/5)

https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by Richard-Gist** [comment]
EOD:  This issue is currently being spiked.  Some consideration for the new DocC stuff announced at WWDC is also being considered as we will probably want to go to that form of developer documentation over jazzy.

The spike so far has revealed that we will be using a branch to host the Github page.  Structure of that branch is still being determined.

**Comment by Tyler-Keith-Thompson** [comment]
I appreciate the line of thinking here. I tend to agree, yeah it's in beta, yeah it may be a little flakey....we should use it. The tutorials, and the web hosting, and the general awesomeness of letting people open the archive is simply too much to pass up on. Plus we'll look pretty hip if we're one of the first to adopt the new DocC stuff.

**Comment by Richard-Gist** [comment]
Created discussion here to talk about it further: https://github.com/wwt/Workflow/discussions/35

**Comment by Richard-Gist** [comment]
EOD: I am currently spiking out what all of this looks like with DocC.  Here is a branch here for what the documentation ends up looking like: https://github.com/wwt/Workflow/tree/docc-spike

And I am trying to get it to show up in Github pages on my test repo: https://github.com/Richard-Gist/actions-testing/tree/gh-pages

**Comment by Richard-Gist** [comment]
EOD: Investigated a 404.html redirect hack and attempted to self host with mac's builtin Apache.  Both did not return promising results.  404 failed to visibly change anything, and we were unable to get to Apache actually loading any self served files.

**Comment by Richard-Gist** [comment]
We are planning to change this issue slightly and/or create a new issue from it.

Ultimately, we are in a place where a little more work with the pipeline would setup the Jazzy docs in a great place that we could call this issue done.  The wiki pages would still be held on Github but the developer docs would be removed and then generated at time of publishing.

We would then have a new issue to track the DocC work separate from the milestone.

**Comment by Tyler-Keith-Thompson** [comment]
I believe you should consider this issue "done" and create a new one for DocC of lower priority. Don't get me wrong, I want to see us invest in DocC. I do not think the ENTIRE team needs to take that on before other more important priorities, like SwiftUI.
