### ISSUE TITLE
Replace SonarCloud with CodeCov

### ISSUE THREAD

**Issue by morganzellers** [wwt/SwiftCurrent#50]
### Is your feature request related to a problem? Please describe.
SonarCloud was not usable by contributors outside of the WWT Organization. SonarCloud was also creating churn for the dev team via issues we did not want to fix and false positives on reports.

### Describe the solution you'd like
We would like to not take on SonarCloud as a tool, but _would_ like to see code coverage for code additions in PRs.

### Describe alternatives you've considered
See discussion #48 for context.

For inspiration see https://github.com/Tyler-Keith-Thompson/CucumberSwift/blob/master/.github/.codecov.yml

**Comment by morganzellers** [comment]
Associated PR #52

**Comment by Richard-Gist** [comment]
A test of after we made it to main.  I must have branched too soon so we didn't get a completely successful test: #53

**Comment by Richard-Gist** [comment]
CodeCov is in and SonarCloud is out.
